# Generated by Django 3.0.1 on 2020-05-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fooitem',
            fields=[
                ('name', models.IntegerField(primary_key=True, serialize=False)),
                ('Quality', models.CharField(max_length=30)),
            ],
        ),
    ]
